name: batt_ds
description: "The BattMobility design system"
version: 0.1.28

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: any
  intl: any
  flutter_svg: any
  phosphor_flutter: ^2.1.0

flutter_localizations:
  sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - packages/batt_ds/assets/icons/car.svg
    - packages/batt_ds/assets/icons/walk.svg
    - packages/batt_ds/assets/icons/range.svg
    - packages/batt_ds/assets/loader/state=1.png
    - packages/batt_ds/assets/loader/state=2.png
    - packages/batt_ds/assets/loader/state=3.png
    - packages/batt_ds/assets/loader/state=4.png
    - packages/batt_ds/assets/loader/state=5.png
    - packages/batt_ds/assets/loader/state=6.png
    - packages/batt_ds/assets/loader/state=7.png
    - packages/batt_ds/assets/loader/state=8.png
    - packages/batt_ds/assets/loader/state=9.png
    - packages/batt_ds/assets/loader/state=10.png
    - packages/batt_ds/assets/loader/state=11.png
    - packages/batt_ds/assets/loader/state=12.png
    - packages/batt_ds/assets/loader/state=13.png
    - packages/batt_ds/assets/loader/state=14.png
    - packages/batt_ds/assets/loader/state=15.png
    - packages/batt_ds/assets/loader/state=16.png
    - packages/batt_ds/assets/loader/state=17.png
    - packages/batt_ds/assets/loader/state=18.png
    - packages/batt_ds/assets/loader/state=19.png
    - packages/batt_ds/assets/loader/state=20.png
    - packages/batt_ds/assets/loader/state=21.png
    - packages/batt_ds/assets/loader/state=22.png
    - packages/batt_ds/assets/loader/state=23.png
    - packages/batt_ds/assets/loader/state=24.png

  fonts:
    - family: LicensePlate
      fonts:
        - asset: packages/batt_ds/assets/fonts/LicensePlate.ttf
    - family: Inter
      fonts:
        - asset: packages/batt_ds/assets/fonts/Inter_24pt-Regular.ttf
    - family: InterBold
      fonts:
        - asset: packages/batt_ds/assets/fonts/Inter_24pt-Bold.ttf