name: batt_ds
description: "The BattMobility design system"
version: 0.0.74

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: any
  intl: any
  flutter_svg: any
  wave: ^0.2.2

flutter_localizations:
  sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - packages/batt_ds/assets/icons/car.svg
    - packages/batt_ds/assets/icons/walk.svg
    - packages/batt_ds/assets/icons/range.svg


  fonts:
    - family: LicensePlate
      fonts:
        - asset: packages/batt_ds/assets/fonts/LicensePlate.ttf
    - family: Inter
      fonts:
        - asset: packages/batt_ds/assets/fonts/Inter_18pt-Regular.ttf